version: "3.8"
services:
  ookla:
    image: romanromanovv/speedserver:commit2
    container_name: ookla-eastera-server
    environment:
      - "TZ=Europa/Madrid"
    ports:
      - "8080:8080"
      - "5060:5060"
      - "80:80"
      - "8080:8080/udp"
      - "5060:5060/udp"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '14'
          memory: 24G
        reservations:
          cpus: '14'
          memory: 24G
